Fix support of PHP CS Fixer 3.0
php-censor/php-censor pull request #414
Opened 2021-07-29 16:45 UTC by StudioMaX

## Contribution type

Bug fix

## Description of change

This adds support of PHP CS Fixer 3.0.

2021-07-31 07:18 UTC, corpsee requested changes

2021-07-31 07:18 UTC, corpsee commented on docs/en/plugins/php_cs_fixer.md
> +* **rules** [string, optional] - Fixer rules (default: `@PSR12`). Cannot be used simultaneously with the `config` option.
I guess it should be `@PSR12` for version `3.x` and `@PSR2` for version `2.x`.

2021-07-31 07:21 UTC, corpsee commented
@StudioMaX Thanks! Could you fix documentation part about default `rules`? Then I can merge PR.

2021-07-31 07:27 UTC, corpsee commented
@StudioMaX Could you also rebase your PR on branch `release-1.3` instead of `master` please?

2021-08-02 18:15 UTC, StudioMaX commented
@corpsee Fixed this. Unfortunately I can't check this manually on 1.3, since I'm already on 2.0.

2021-08-03 02:42 UTC, corpsee commented
Thanks! Version `1.3` I will test it myself. :+1:

2021-08-03 02:43 UTC, merged